### ISSUE TITLE
PowerA Xbox One Wired Controller Unresponsive

### ISSUE THREAD

**Issue by akrodger** [paroj/xpad#58] opened 2016-12-27 13:07 UTC
I have a wired usb PowerA Xbox One controller. Device ID is 24c6:543a.

Just spent a few hours reading the source code on this driver and couldn't figure out what was making this happen. Before installation, the device was not recognized at all, after installation, I was able to find the device as a joypad at js0. Running jstest, I get the usual testing set up, but nothing responds. Works fine with my logitech USB controller on the same port. Confirmed the PowerA controller was not broken by checking on a Windows 10 machine. Is there a patch for this anyone has managed to get working?

If no such patch exists, I have some free time over this winter. Is there any way I can help the project and maybe get this controller working? (It was a Christmas gift, I rather further linux support than take back a gift to the store.)

Thanks!
-Bram

**Comment by paroj** [comment] 2016-12-27 13:49
duplicate of #48

**Closed by paroj** 2016-12-27 13:49 UTC
