### ISSUE TITLE
Xbox One issues

### ISSUE THREAD

**Issue by enricostano** [paroj/xpad#26] opened 2016-03-18 08:26 UTC
Hi! We're having troubles with the latest Xbox One controller. You can find more details here https://bbs.archlinux.org/viewtopic.php?id=208569

Can someone shade some light? Thanks! :smiley:

**Comment by john5788** [comment] 2016-03-22 18:21
Duplicate of https://github.com/paroj/xpad/issues/19

**Comment by enricostano** [comment] 2016-03-22 19:26
This worked for me https://github.com/ValveSoftware/steamos_kernel/blob/bcb20f5bbbe333ef12d5efda6207e7b84578e85d/drivers/input/joystick/xpad.c

**Closed** 2016-03-22 19:26 UTC
