### ISSUE TITLE
Support for a new Xbox one controller wireless receiver

### ISSUE THREAD

**Issue by cszipper** [paroj/xpad#90] opened 2018-01-06 09:50 UTC
Hey, I have got a Xbox one controller with a wireless receiver but it can't work with this driver. I noticed that this product id is not included in xpad_devices.
> kernel: [ 2359.371456] usb 3-6: New USB device found, idVendor=045e, idProduct=02fe
> kernel: [ 2359.371457] usb 3-6: New USB device strings: Mfr=1, Product=2, SerialNumber=3
> kernel: [ 2359.371457] usb 3-6: Product: XBOX ACC
> kernel: [ 2359.371458] usb 3-6: Manufacturer: Microsoft Inc.

and this is the information of the controller

> kernel: [ 6265.365356] usb 3-6: New USB device found, idVendor=045e, idProduct=02ea
> kernel: [ 6265.365357] usb 3-6: New USB device strings: Mfr=1, Product=2, SerialNumber=3
> kernel: [ 6265.365359] usb 3-6: Product: Controller
> kernel: [ 6265.365359] usb 3-6: Manufacturer: Microsoft

**Comment by perillamint** [comment] 2018-01-10 14:43
It seems duplicate of #14.

**Comment by paroj** [comment] 2018-01-10 16:56
yes, the WiFi dongle is currently not supported. And we did not have much progress in the mentioned issues - except for users switching to the bluetooth version.

**Closed by paroj** 2018-01-10 16:56 UTC
